/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 9.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f8b548a3-6503-41c8-b42d-fc593cf21539
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceIPG'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - clockDriver: 'kADC_ClockDriver4'
      - samplePeriodMode: 'kADC_SamplePeriodShort4Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount4'
      - enableHardwareTrigger: 'hardware'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'false'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.13'
        - channelName: 'CUR_U_CH'
        - channelGroup: '0'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.11'
        - channelName: 'VOLT_BUS_CH'
        - channelGroup: '1'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'false'
      - 2:
        - channelNumber: 'IN.12'
        - channelName: 'SYS_TEMP_CH'
        - channelGroup: '2'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC1_config = {
  .enableOverWrite = false,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort4Clocks,
  .clockSource = kADC_ClockSourceIPG,
  .clockDriver = kADC_ClockDriver4,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC1_channels_config[3] = {
  {
    .channelNumber = CUR_U_CH,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = VOLT_BUS_CH,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = SYS_TEMP_CH,
    .enableInterruptOnConversionCompleted = false
  }
};
static void ADC1_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(ADC1_PERIPHERAL, &ADC1_config);
  /* Configure ADC1 peripheral to average 4 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC1_PERIPHERAL, kADC_HardwareAverageCount4);
  /* Enable ADC1 hardware trigger. */
  ADC_EnableHardwareTrigger(ADC1_PERIPHERAL, true);
  /* Initialize ADC1 channel 13. */
  ADC_SetChannelConfig(ADC1_PERIPHERAL, ADC1_CH0_CONTROL_GROUP, &ADC1_channels_config[0]);
  /* Initialize ADC1 channel 11. */
  ADC_SetChannelConfig(ADC1_PERIPHERAL, ADC1_CH1_CONTROL_GROUP, &ADC1_channels_config[1]);
  /* Initialize ADC1 channel 12. */
  ADC_SetChannelConfig(ADC1_PERIPHERAL, ADC1_CH2_CONTROL_GROUP, &ADC1_channels_config[2]);
}

/***********************************************************************************************************************
 * ADC2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC2'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC2'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceIPG'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - clockDriver: 'kADC_ClockDriver4'
      - samplePeriodMode: 'kADC_SamplePeriodShort4Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount4'
      - enableHardwareTrigger: 'hardware'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'false'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.4'
        - channelName: 'CUR_W_CH'
        - channelGroup: '0'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.2'
        - channelName: 'Light_V_Out_CH'
        - channelGroup: '1'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC2_config = {
  .enableOverWrite = false,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort4Clocks,
  .clockSource = kADC_ClockSourceIPG,
  .clockDriver = kADC_ClockDriver4,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC2_channels_config[2] = {
  {
    .channelNumber = CUR_W_CH,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = Light_V_Out_CH,
    .enableInterruptOnConversionCompleted = false
  }
};
static void ADC2_init(void) {
  /* Initialize ADC2 peripheral. */
  ADC_Init(ADC2_PERIPHERAL, &ADC2_config);
  /* Configure ADC2 peripheral to average 4 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC2_PERIPHERAL, kADC_HardwareAverageCount4);
  /* Enable ADC2 hardware trigger. */
  ADC_EnableHardwareTrigger(ADC2_PERIPHERAL, true);
  /* Initialize ADC2 channel 4. */
  ADC_SetChannelConfig(ADC2_PERIPHERAL, ADC2_CH0_CONTROL_GROUP, &ADC2_channels_config[0]);
  /* Initialize ADC2 channel 2. */
  ADC_SetChannelConfig(ADC2_PERIPHERAL, ADC2_CH1_CONTROL_GROUP, &ADC2_channels_config[1]);
}

/***********************************************************************************************************************
 * ADC_ETC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_ETC'
- type: 'adc_etc'
- mode: 'ADC_ETC_SW'
- custom_name_enabled: 'false'
- type_id: 'adc_etc_05e3d3ed2376fa5bde10b24efc9ee456'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_ETC'
- config_sets:
  - fsl_adc_etc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
        - clockPreDivider: '1'
      - dmaMode: 'kADC_ETC_TrigDMAWithLatchedSignal'
    - tscConfig:
      - enableTSCBypass: 'false'
      - enableTSC0Trigger: 'false'
      - TSC0triggerPriority: '0'
      - enableTSC1Trigger: 'false'
      - TSC1triggerPriority: '0'
    - triggers_config:
      - 0:
        - triggerNameValue: 'TC_0'
        - initializeTrigger: 'true'
        - trigger: 'XBAR0_TRIG.0'
        - triggerPriority: '0'
        - enableSWTriggerMode: 'false'
        - enableSyncMode: 'true'
        - enableDMA: 'false'
        - initialDelay_str: '0'
        - sampleIntervalDelay_str: '0'
        - triggerChain:
          - 0:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '0'
            - channelNumber: 'ADC1.IN.13'
            - e_InterruptEnable: 'kADC_ETC_InterruptDisable'
          - 1:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '1'
            - channelNumber: 'ADC1.IN.11'
            - e_InterruptEnable: 'kADC_ETC_Done0InterruptEnable'
          - 2:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '2'
            - channelNumber: 'ADC1.IN.12'
            - e_InterruptEnable: 'kADC_ETC_InterruptDisable'
      - 1:
        - triggerNameValue: 'TC_1'
        - initializeTrigger: 'true'
        - trigger: 'XBAR1_TRIG.0'
        - triggerPriority: '0'
        - enableSWTriggerMode: 'false'
        - enableSyncMode: 'true'
        - enableDMA: 'false'
        - initialDelay_str: '0'
        - sampleIntervalDelay_str: '0'
        - triggerChain:
          - 0:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '0'
            - channelNumber: 'ADC2.IN.4'
            - e_InterruptEnable: 'kADC_ETC_InterruptDisable'
          - 1:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '1'
            - channelNumber: 'ADC2.IN.2'
            - e_InterruptEnable: 'kADC_ETC_InterruptDisable'
    - enableInterrupt: 'true'
    - adc_etc_interrupt_0:
      - IRQn: 'ADC_ETC_IRQ0_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_etc_interrupt_err:
      - IRQn: 'ADC_ETC_ERROR_IRQ_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ADC_ETC configuration */
const adc_etc_config_t ADC_ETC_config = {
  .clockPreDivider = 1,
  .dmaMode = kADC_ETC_TrigDMAWithLatchedSignal,
  .enableTSCBypass = false,
  .enableTSC0Trigger = false,
  .enableTSC1Trigger = false,
  .TSC0triggerPriority = 0,
  .TSC1triggerPriority = 0,
  .XBARtriggerMask = 17
};
/* ADC_ETC triggers configuration */
const adc_etc_trigger_config_t ADC_ETC_trigger_config[2] = {
  {
    .triggerPriority = 0,
    .enableSWTriggerMode = false,
    .enableSyncMode = true,
    .initialDelay = 0,
    .sampleIntervalDelay = 0,
    .triggerChainLength = 2
  },
  {
    .triggerPriority = 0,
    .enableSWTriggerMode = false,
    .enableSyncMode = true,
    .initialDelay = 0,
    .sampleIntervalDelay = 0,
    .triggerChainLength = 1
  }
};
/* ADC_ETC chain configurations for appropriate (see name of these arrays) trigger configuration */
const adc_etc_trigger_chain_config_t ADC_ETC_TC_0_chain_config[3] = {
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 1,
    .ADCChannelSelect = 13,
    .InterruptEnable = kADC_ETC_InterruptDisable,
  },
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 2,
    .ADCChannelSelect = 11,
    .InterruptEnable = kADC_ETC_Done0InterruptEnable,
  },
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 4,
    .ADCChannelSelect = 12,
    .InterruptEnable = kADC_ETC_InterruptDisable,
  }
};
const adc_etc_trigger_chain_config_t ADC_ETC_TC_1_chain_config[2] = {
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 1,
    .ADCChannelSelect = 4,
    .InterruptEnable = kADC_ETC_InterruptDisable,
  },
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 2,
    .ADCChannelSelect = 2,
    .InterruptEnable = kADC_ETC_InterruptDisable,
  }
};

static void ADC_ETC_init(void) {
  /* ADC_ETC initialization */
  ADC_ETC_Init(ADC_ETC_PERIPHERAL, &ADC_ETC_config);
  /* Initialize ADC_ETC trigger 0. */
  ADC_ETC_SetTriggerConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, &ADC_ETC_trigger_config[ADC_ETC_TC_0]);
  /* Initialize ADC_ETC chain configuration for trigger 0. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 0U, &ADC_ETC_TC_0_chain_config[0]);
  /* Initialize ADC_ETC chain configuration for trigger 0. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 1U, &ADC_ETC_TC_0_chain_config[1]);
  /* Initialize ADC_ETC chain configuration for trigger 0. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 2U, &ADC_ETC_TC_0_chain_config[2]);
  /* Initialize ADC_ETC trigger 4. */
  ADC_ETC_SetTriggerConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_1_TG, &ADC_ETC_trigger_config[ADC_ETC_TC_1]);
  /* Initialize ADC_ETC chain configuration for trigger 4. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_1_TG, 0U, &ADC_ETC_TC_1_chain_config[0]);
  /* Initialize ADC_ETC chain configuration for trigger 4. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_1_TG, 1U, &ADC_ETC_TC_1_chain_config[1]);
  /* Interrupt ADC_ETC_IRQ0_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(ADC_ETC_ADC_ETC_0_IRQN);  function call. */
  /* Interrupt ADC_ETC_ERROR_IRQ_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(ADC_ETC_ADC_ETC_ERROR_IRQN);  function call. */
}

/***********************************************************************************************************************
 * CMP1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CMP1'
- type: 'cmp'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'cmp_306724f57b92dbe1771f1514089d2b18'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CMP1'
- config_sets:
  - fsl_filter:
    - filter_config:
      - filteringOptions: 'enableFilter'
      - clockSource: 'SystemClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - filterPeriod: '100'
      - filterCount: '7'
  - fsl_cmp:
    - main_config:
      - explicitEnableCmp: 'false'
      - hysteresisMode: 'kCMP_HysteresisLevel3'
      - enableHighSpeed: 'false'
      - enableInvertOutput: 'false'
      - useUnfilteredOutput: 'false'
      - enablePinOut: 'false'
    - positiveChannel: 'IN.7'
    - negativeChannel: 'IN.6'
  - fsl_dac:
    - enableDAC: 'true'
    - dac_config:
      - referenceVoltageSource: 'DAC_6bit_VIN2'
      - DACValue: '4'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* CMP1 main configuration */
const cmp_config_t CMP1_config = {
  .enableCmp = false,
  .hysteresisMode = kCMP_HysteresisLevel3,
  .enableHighSpeed = false,
  .enableInvertOutput = false,
  .useUnfilteredOutput = false,
  .enablePinOut = false,
};
/* Configuration of the DAC sub-module, used in the CMP_SetDACConfig() function */
const cmp_dac_config_t CMP1_dac_config = {
  .referenceVoltageSource = kCMP_VrefSourceVin2,
  .DACValue = 3U
};
/* Configuration of the filter sub-module, used in the CMP_SetFilterConfig() function */
const cmp_filter_config_t CMP1_filter_config = {
  .enableSample = false,
  .filterCount = 7U,
  .filterPeriod = 100U
};

static void CMP1_init(void) {
  /* Initialize CMP main sub-module functionality */
  CMP_Init(CMP1_PERIPHERAL, &CMP1_config);
  /* Set up internal DAC sub-module, that can be used as input 7 of the CMP both inputs. */
  CMP_SetDACConfig(CMP1_PERIPHERAL, &CMP1_dac_config);
  /* Configures Filter block settings */
  CMP_SetFilterConfig(CMP1_PERIPHERAL, &CMP1_filter_config);
  /* Initialize CMP main sub-module functionality */
  CMP_SetInputChannels(CMP1_PERIPHERAL, CMP1_POSITIVE_INPUT_NUMBER, CMP1_NEGATIVE_INPUT_NUMBER);
}

/***********************************************************************************************************************
 * ENC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ENC1'
- type: 'enc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'enc_a31ae546b0cbfc3aa2c35851e1fcb3b8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ENC1'
- config_sets:
  - fsl_enc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - decoderWorkMode: 'kENC_DecoderWorkAsNormalMode'
      - enableReverseDirection: 'false'
      - posInitialization:
        - HOMETriggerMode: 'kENC_HOMETriggerDisabled'
        - INDEXTriggerMode: 'kENC_INDEXTriggerDisabled'
        - positionInitialValue: '0'
      - triggerAction: 'updateHoldRegs'
      - positionMatchConfig:
        - positionMatchMode: 'kENC_POSMATCHOnPositionCounterEqualToComapreValue'
        - positionCompareValue: '0xFFFFFFFF'
      - modulusConfig:
        - revolutionCountCondition: 'kENC_RevolutionCountOnINDEXPulse'
        - enableModuloCountMode: 'true'
        - positionModulusValue: '0'
      - wdogConfig:
        - enableWatchdog: 'false'
      - filter_config_t:
        - enableFilter: 'true'
        - filterPeriod: '1'
        - filterCount: '3'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '1'
        - enable_custom_name: 'false'
      - enable_home_irq: 'false'
      - interrupt_home:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_wdog_irq: 'false'
      - interrupt_wdog:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_index_irq: 'false'
      - interrupt_index:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ENC configuration */
enc_config_t ENC1_config = {
  .decoderWorkMode = kENC_DecoderWorkAsNormalMode,
  .enableReverseDirection = false,
  .HOMETriggerMode = kENC_HOMETriggerDisabled,
  .INDEXTriggerMode = kENC_INDEXTriggerDisabled,
  .positionInitialValue = 0,
  .enableTRIGGERClearPositionCounter = false,
  .enableTRIGGERClearHoldPositionCounter = true,
  .positionMatchMode = kENC_POSMATCHOnPositionCounterEqualToComapreValue,
  .positionCompareValue = 4294967295,
  .revolutionCountCondition = kENC_RevolutionCountOnINDEXPulse,
  .enableModuloCountMode = true,
  .positionModulusValue = 0,
  .enableWatchdog = false,
  .watchdogTimeoutValue = 0,
  .filterCount = 0,
  .filterSamplePeriod = 1
};

static void ENC1_init(void) {
  /* ENC initialization */
  ENC_Init(ENC1_PERIPHERAL, &ENC1_config);
}

/***********************************************************************************************************************
 * ENC2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ENC2'
- type: 'enc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'enc_a31ae546b0cbfc3aa2c35851e1fcb3b8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ENC2'
- config_sets:
  - fsl_enc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - decoderWorkMode: 'kENC_DecoderWorkAsNormalMode'
      - enableReverseDirection: 'false'
      - posInitialization:
        - HOMETriggerMode: 'kENC_HOMETriggerDisabled'
        - INDEXTriggerMode: 'kENC_INDEXTriggerOnRisingEdge'
        - positionInitialValue: '0'
      - triggerAction: 'updateHoldRegs'
      - positionMatchConfig:
        - positionMatchMode: 'kENC_POSMATCHOnPositionCounterEqualToComapreValue'
        - positionCompareValue: '0xFFFFFFFF'
      - modulusConfig:
        - revolutionCountCondition: 'kENC_RevolutionCountOnINDEXPulse'
        - enableModuloCountMode: 'false'
      - wdogConfig:
        - enableWatchdog: 'false'
      - filter_config_t:
        - enableFilter: 'true'
        - filterPeriod: '1'
        - filterCount: '3'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'ENC2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_home_irq: 'false'
      - interrupt_home:
        - IRQn: 'ENC2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_wdog_irq: 'false'
      - interrupt_wdog:
        - IRQn: 'ENC2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_index_irq: 'false'
      - interrupt_index:
        - IRQn: 'ENC2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ENC configuration */
enc_config_t ENC2_config = {
  .decoderWorkMode = kENC_DecoderWorkAsNormalMode,
  .enableReverseDirection = false,
  .HOMETriggerMode = kENC_HOMETriggerDisabled,
  .INDEXTriggerMode = kENC_INDEXTriggerOnRisingEdge,
  .positionInitialValue = 0,
  .enableTRIGGERClearPositionCounter = false,
  .enableTRIGGERClearHoldPositionCounter = true,
  .positionMatchMode = kENC_POSMATCHOnPositionCounterEqualToComapreValue,
  .positionCompareValue = 4294967295,
  .revolutionCountCondition = kENC_RevolutionCountOnINDEXPulse,
  .enableModuloCountMode = false,
  .positionModulusValue = 0,
  .enableWatchdog = false,
  .watchdogTimeoutValue = 0,
  .filterCount = 0,
  .filterSamplePeriod = 1
};

static void ENC2_init(void) {
  /* ENC initialization */
  ENC_Init(ENC2_PERIPHERAL, &ENC2_config);
}

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO1_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO1_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int0: 'false'
    - gpio_interrupt_int0:
      - IRQn: 'GPIO1_INT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int1: 'false'
    - gpio_interrupt_int1:
      - IRQn: 'GPIO1_INT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int2: 'false'
    - gpio_interrupt_int2:
      - IRQn: 'GPIO1_INT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int3: 'false'
    - gpio_interrupt_int3:
      - IRQn: 'GPIO1_INT3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int4: 'false'
    - gpio_interrupt_int4:
      - IRQn: 'GPIO1_INT4_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int5: 'false'
    - gpio_interrupt_int5:
      - IRQn: 'GPIO1_INT5_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int6: 'false'
    - gpio_interrupt_int6:
      - IRQn: 'GPIO1_INT6_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int7: 'false'
    - gpio_interrupt_int7:
      - IRQn: 'GPIO1_INT7_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO1_init(void) {
  /* Make sure, the clock gate for GPIO1 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO1_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO1_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO1_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO1_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * GPIO2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO2'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO2'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO2_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO2_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO2_init(void) {
  /* Make sure, the clock gate for GPIO2 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO2_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO2_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO2_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO2_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'interrupts'
- custom_name_enabled: 'false'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '230400'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - interruptsCfg:
    - interrupts: 'kLPUART_RxDataRegFullInterruptEnable kLPUART_IdleLineInterruptEnable'
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'LPUART1_IRQn'
        - enable_interrrupt: 'noInit'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 230400UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  LPUART_EnableInterrupts(LPUART1_PERIPHERAL, kLPUART_RxDataRegFullInterruptEnable | kLPUART_IdleLineInterruptEnable);
  /* Interrupt vector LPUART1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(LPUART1_SERIAL_RX_TX_IRQN, LPUART1_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt LPUART1_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(LPUART1_SERIAL_RX_TX_IRQN);  function call. */
}

/***********************************************************************************************************************
 * PWM1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PWM1'
- type: 'pwm'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pwm_403b1696012c269dda52095c45493820'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PWM1'
- config_sets:
  - fsl_pwm:
    - clockSource: 'SystemClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - submodules:
      - 0:
        - sm: 'kPWM_Module_0'
        - sm_id: 'PWM_U'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_1'
          - pwmFreq: '20kHz'
          - pairOperation: 'kPWM_ComplementaryPwmA'
          - operationMode: 'kPWM_CenterAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadPwmHalfAndFullCycle'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - enableWait: 'false'
          - outputTrigger_sel: 'kPWM_ValueRegister_0 kPWM_ValueRegister_1'
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: 'kPWM_CompareVal0InterruptEnable kPWM_CompareVal1InterruptEnable'
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'PWM_UH'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'PWM_UL'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'true'
        - common_interrupt:
          - IRQn: 'PWM1_0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '4'
          - enable_custom_name: 'true'
          - handler_custom_name: 'PWM_MOTOR_ISR'
      - 1:
        - sm: 'kPWM_Module_1'
        - sm_id: 'PWM_V'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_1'
          - pwmFreq: '20 kHz'
          - pairOperation: 'kPWM_ComplementaryPwmA'
          - operationMode: 'kPWM_CenterAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadPwmHalfAndFullCycle'
          - reloadSelect: 'kPWM_MasterReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - enableWait: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'PWM_VH'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'PWM_VL'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM1_1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 2:
        - sm: 'kPWM_Module_2'
        - sm_id: 'PWM_W'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_1'
          - pwmFreq: '20 kHz'
          - pairOperation: 'kPWM_ComplementaryPwmA'
          - operationMode: 'kPWM_CenterAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadPwmHalfAndFullCycle'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - enableWait: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'PWM_WH'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'PWM_WL'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '150'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM1_2_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - faultChannels:
      - 0:
        - commonFaultSetting:
          - clockSource: 'kPWM_BusClock'
          - faultFilterPeriod: '1'
          - faultFilterCount: '10'
          - faultGlitchStretch: 'true'
        - faults:
          - 0:
            - fault_id: 'Fault0'
            - faultClearingMode: 'kPWM_ManualSafety'
            - faultLevelR: 'high'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_RecoverFullCycle'
            - fault_int_source: 'true'
          - 1:
            - fault_id: 'Fault1'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'high'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 2:
            - fault_id: 'Fault2'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'high'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 3:
            - fault_id: 'Fault3'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'high'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
    - fault_error_interruptEn: 'true'
    - fault_error_interrupt:
      - IRQn: 'PWM1_FAULT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '0'
      - enable_custom_name: 'true'
      - handler_custom_name: 'PWM_MOTOR_FAULT_ISR'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* PWM main configuration */
pwm_config_t PWM1_PWM_U_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_1,
  .pairOperation = kPWM_ComplementaryPwmA,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadPwmHalfAndFullCycle,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
  .enableWait = false
};

pwm_signal_param_t PWM1_PWM_U_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
};

pwm_config_t PWM1_PWM_V_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_1,
  .pairOperation = kPWM_ComplementaryPwmA,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadPwmHalfAndFullCycle,
  .reloadSelect = kPWM_MasterReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
  .enableWait = false
};

pwm_signal_param_t PWM1_PWM_V_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
};

pwm_config_t PWM1_PWM_W_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_1,
  .pairOperation = kPWM_ComplementaryPwmA,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadPwmHalfAndFullCycle,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
  .enableWait = false
};

pwm_signal_param_t PWM1_PWM_W_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 150U
  },
};

const pwm_fault_input_filter_param_t PWM1_faultInputFilter_config = {
  .faultFilterPeriod = 1U,
  .faultFilterCount = 10U,
  .faultGlitchStretch = true
};
const pwm_fault_param_t PWM1_Fault0_fault_config = {
  .faultClearingMode = kPWM_ManualSafety,
  .faultLevel = true,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_RecoverFullCycle
};
const pwm_fault_param_t PWM1_Fault1_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = true,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM1_Fault2_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = true,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM1_Fault3_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = true,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};

static void PWM1_init(void) {
  /* Initialize PWM submodule PWM_U main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_PWM_U, &PWM1_PWM_U_config);
  /* Initialize PWM submodule PWM_V main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_PWM_V, &PWM1_PWM_V_config);
  /* Initialize PWM submodule PWM_W main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_PWM_W, &PWM1_PWM_W_config);
  /* Initialize fault input filter configuration */
  PWM_SetupFaultInputFilter(PWM1_PERIPHERAL, &PWM1_faultInputFilter_config);
  /* Initialize fault channel 0 fault Fault0 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT0, &PWM1_Fault0_fault_config);
  /* Initialize fault channel 0 fault Fault1 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT1, &PWM1_Fault1_fault_config);
  /* Initialize fault channel 0 fault Fault2 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT2, &PWM1_Fault2_fault_config);
  /* Initialize fault channel 0 fault Fault3 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT3, &PWM1_Fault3_fault_config);
  /* Initialize submodule PWM_U channel PWM_UH output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_U, PWM1_PWM_U_PWM_UH, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Initialize submodule PWM_U channel PWM_UL output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_U, PWM1_PWM_U_PWM_UL, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Initialize submodule PWM_V channel PWM_VH output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_V, PWM1_PWM_V_PWM_VH, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Initialize submodule PWM_V channel PWM_VL output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_V, PWM1_PWM_V_PWM_VL, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Initialize submodule PWM_W channel PWM_WH output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_W, PWM1_PWM_W_PWM_WH, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Initialize submodule PWM_W channel PWM_WL output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM1_PERIPHERAL, PWM1_PWM_W, PWM1_PWM_W_PWM_WL, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Enable faults interrupts */
  PWM_EnableInterrupts(PWM1_PERIPHERAL, PWM1_PWM_U, (kPWM_Fault0InterruptEnable));
  /* Initialize deadtime logic input for the channel PWM_UH */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_U, PWM1_PWM_U_PWM_UH, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel PWM_UL */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_U, PWM1_PWM_U_PWM_UL, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel PWM_VH */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_V, PWM1_PWM_V_PWM_VH, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel PWM_VL */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_V, PWM1_PWM_V_PWM_VL, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel PWM_WH */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_W, PWM1_PWM_W_PWM_WH, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel PWM_WL */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_PWM_W, PWM1_PWM_W_PWM_WL, kPWM_UsePwm);
  /* Setup PWM output setting for submodule PWM_U */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_PWM_U, PWM1_PWM_U_pwm_function_config, 2U, kPWM_CenterAligned, PWM1_PWM_U_COUNTER_FREQ_HZ, PWM1_PWM_U_SM_CLK_SOURCE_FREQ_HZ);
  /* Setup PWM output setting for submodule PWM_V */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_PWM_V, PWM1_PWM_V_pwm_function_config, 2U, kPWM_CenterAligned, PWM1_PWM_V_COUNTER_FREQ_HZ, PWM1_PWM_V_SM_CLK_SOURCE_FREQ_HZ);
  /* Setup PWM output setting for submodule PWM_W */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_PWM_W, PWM1_PWM_W_pwm_function_config, 2U, kPWM_CenterAligned, PWM1_PWM_W_COUNTER_FREQ_HZ, PWM1_PWM_W_SM_CLK_SOURCE_FREQ_HZ);
  /* Initialize output trigger for VAL0 compare of submodule PWM_U */
  PWM_OutputTriggerEnable(PWM1_PERIPHERAL, PWM1_PWM_U, kPWM_ValueRegister_0, true);
  /* Initialize output trigger for VAL1 compare of submodule PWM_U */
  PWM_OutputTriggerEnable(PWM1_PERIPHERAL, PWM1_PWM_U, kPWM_ValueRegister_1, true);
  /* Enable interrupts from main config of the submodule PWM_U */
  PWM_EnableInterrupts(PWM1_PERIPHERAL, PWM1_PWM_U, (kPWM_CompareVal0InterruptEnable | kPWM_CompareVal1InterruptEnable));
  /* Interrupt vector PWM1_0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(PWM1_COMMON_SM_0_IRQN, PWM1_COMMON_SM_0_IRQ_PRIORITY);
  /* Enable interrupt PWM1_0_IRQn request in the NVIC. */
  EnableIRQ(PWM1_COMMON_SM_0_IRQN);
  /* Interrupt vector PWM1_FAULT_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(PWM1_FAULT_ERROR_IRQN, PWM1_FAULT_ERROR_IRQ_PRIORITY);
  /* Enable interrupt PWM1_FAULT_IRQn request in the NVIC. */
  EnableIRQ(PWM1_FAULT_ERROR_IRQN);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
      - 13: []
      - 14: []
      - 15: []
      - 16: []
      - 17: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO4'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO4'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO4_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO4_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO4_init(void) {
  /* Make sure, the clock gate for GPIO4 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO4_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO4_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO4_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO4_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * ENC3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ENC3'
- type: 'enc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'enc_a31ae546b0cbfc3aa2c35851e1fcb3b8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ENC3'
- config_sets:
  - fsl_enc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - decoderWorkMode: 'kENC_DecoderWorkAsSignalPhaseCountMode'
      - enableReverseDirection: 'false'
      - posInitialization:
        - HOMETriggerMode: 'kENC_HOMETriggerDisabled'
        - INDEXTriggerMode: 'kENC_INDEXTriggerDisabled'
        - positionInitialValue: '0'
      - triggerAction: 'updateHoldRegs'
      - positionMatchConfig:
        - positionMatchMode: 'kENC_POSMATCHOnPositionCounterEqualToComapreValue'
        - positionCompareValue: '0xFFFFFFFF'
      - modulusConfig:
        - revolutionCountCondition: 'kENC_RevolutionCountOnINDEXPulse'
        - enableModuloCountMode: 'false'
      - wdogConfig:
        - enableWatchdog: 'false'
      - filter_config_t:
        - enableFilter: 'true'
        - filterPeriod: '1'
        - filterCount: '3'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'ENC3_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_home_irq: 'false'
      - interrupt_home:
        - IRQn: 'ENC3_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_wdog_irq: 'false'
      - interrupt_wdog:
        - IRQn: 'ENC3_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_index_irq: 'false'
      - interrupt_index:
        - IRQn: 'ENC3_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ENC configuration */
enc_config_t ENC3_config = {
  .decoderWorkMode = kENC_DecoderWorkAsSignalPhaseCountMode,
  .enableReverseDirection = false,
  .HOMETriggerMode = kENC_HOMETriggerDisabled,
  .INDEXTriggerMode = kENC_INDEXTriggerDisabled,
  .positionInitialValue = 0,
  .enableTRIGGERClearPositionCounter = false,
  .enableTRIGGERClearHoldPositionCounter = true,
  .positionMatchMode = kENC_POSMATCHOnPositionCounterEqualToComapreValue,
  .positionCompareValue = 4294967295,
  .revolutionCountCondition = kENC_RevolutionCountOnINDEXPulse,
  .enableModuloCountMode = false,
  .positionModulusValue = 0,
  .enableWatchdog = false,
  .watchdogTimeoutValue = 0,
  .filterCount = 0,
  .filterSamplePeriod = 1
};

static void ENC3_init(void) {
  /* ENC initialization */
  ENC_Init(ENC3_PERIPHERAL, &ENC3_config);
}

/***********************************************************************************************************************
 * ENC4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ENC4'
- type: 'enc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'enc_a31ae546b0cbfc3aa2c35851e1fcb3b8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ENC4'
- config_sets:
  - fsl_enc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - decoderWorkMode: 'kENC_DecoderWorkAsSignalPhaseCountMode'
      - enableReverseDirection: 'false'
      - posInitialization:
        - HOMETriggerMode: 'kENC_HOMETriggerDisabled'
        - INDEXTriggerMode: 'kENC_INDEXTriggerDisabled'
        - positionInitialValue: '0'
      - triggerAction: ''
      - positionMatchConfig:
        - positionMatchMode: 'kENC_POSMATCHOnPositionCounterEqualToComapreValue'
        - positionCompareValue: '0xFFFFFFFF'
      - modulusConfig:
        - revolutionCountCondition: 'kENC_RevolutionCountOnINDEXPulse'
        - enableModuloCountMode: 'false'
      - wdogConfig:
        - enableWatchdog: 'false'
      - filter_config_t:
        - enableFilter: 'true'
        - filterPeriod: '1'
        - filterCount: '3'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'ENC4_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_home_irq: 'false'
      - interrupt_home:
        - IRQn: 'ENC4_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_wdog_irq: 'false'
      - interrupt_wdog:
        - IRQn: 'ENC4_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_index_irq: 'false'
      - interrupt_index:
        - IRQn: 'ENC4_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ENC configuration */
enc_config_t ENC4_config = {
  .decoderWorkMode = kENC_DecoderWorkAsSignalPhaseCountMode,
  .enableReverseDirection = false,
  .HOMETriggerMode = kENC_HOMETriggerDisabled,
  .INDEXTriggerMode = kENC_INDEXTriggerDisabled,
  .positionInitialValue = 0,
  .enableTRIGGERClearPositionCounter = false,
  .enableTRIGGERClearHoldPositionCounter = false,
  .positionMatchMode = kENC_POSMATCHOnPositionCounterEqualToComapreValue,
  .positionCompareValue = 4294967295,
  .revolutionCountCondition = kENC_RevolutionCountOnINDEXPulse,
  .enableModuloCountMode = false,
  .positionModulusValue = 0,
  .enableWatchdog = false,
  .watchdogTimeoutValue = 0,
  .filterCount = 0,
  .filterSamplePeriod = 1
};

static void ENC4_init(void) {
  /* ENC initialization */
  ENC_Init(ENC4_PERIPHERAL, &ENC4_config);
}

/***********************************************************************************************************************
 * GPIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO3'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO3'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO3_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO3_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO3_init(void) {
  /* Make sure, the clock gate for GPIO3 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO3_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO3_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO3_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO3_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * LPUART3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART3'
- type: 'lpuart'
- mode: 'interrupts'
- custom_name_enabled: 'false'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART3'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '921600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - interruptsCfg:
    - interrupts: 'kLPUART_RxDataRegFullInterruptEnable kLPUART_IdleLineInterruptEnable'
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'LPUART3_IRQn'
        - enable_interrrupt: 'noInit'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART3_config = {
  .baudRate_Bps = 921600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART3_init(void) {
  LPUART_Init(LPUART3_PERIPHERAL, &LPUART3_config, LPUART3_CLOCK_SOURCE);
  LPUART_EnableInterrupts(LPUART3_PERIPHERAL, kLPUART_RxDataRegFullInterruptEnable | kLPUART_IdleLineInterruptEnable);
  /* Interrupt vector LPUART3_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(LPUART3_SERIAL_RX_TX_IRQN, LPUART3_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt LPUART3_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(LPUART3_SERIAL_RX_TX_IRQN);  function call. */
}

/***********************************************************************************************************************
 * GPIO5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO5'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO5'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO5_Combined_0_15_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO5_Combined_16_31_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO5_init(void) {
  /* Make sure, the clock gate for GPIO5 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO5_Combined_0_15_IRQn request in the NVIC. */
  EnableIRQ(GPIO5_GPIO_COMB_0_15_IRQN);
  /* Enable interrupt GPIO5_Combined_16_31_IRQn request in the NVIC. */
  EnableIRQ(GPIO5_GPIO_COMB_16_31_IRQN);
}

/***********************************************************************************************************************
 * LPUART4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART4'
- type: 'lpuart'
- mode: 'interrupts'
- custom_name_enabled: 'false'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART4'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '460800'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - interruptsCfg:
    - interrupts: 'kLPUART_RxDataRegFullInterruptEnable kLPUART_IdleLineInterruptEnable'
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'LPUART4_IRQn'
        - enable_interrrupt: 'noInit'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART4_config = {
  .baudRate_Bps = 460800UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART4_init(void) {
  LPUART_Init(LPUART4_PERIPHERAL, &LPUART4_config, LPUART4_CLOCK_SOURCE);
  LPUART_EnableInterrupts(LPUART4_PERIPHERAL, kLPUART_RxDataRegFullInterruptEnable | kLPUART_IdleLineInterruptEnable);
  /* Interrupt vector LPUART4_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(LPUART4_SERIAL_RX_TX_IRQN, LPUART4_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt LPUART4_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(LPUART4_SERIAL_RX_TX_IRQN);  function call. */
}

/***********************************************************************************************************************
 * PWM4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PWM4'
- type: 'pwm'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pwm_403b1696012c269dda52095c45493820'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PWM4'
- config_sets:
  - fsl_pwm:
    - clockSource: 'SystemClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - submodules:
      - 0:
        - sm: 'kPWM_Module_2'
        - sm_id: 'SM0'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_1'
          - pwmFreq: '10 kHz'
          - pairOperation: 'kPWM_Independent'
          - operationMode: 'kPWM_CenterAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadPwmHalfAndFullCycle'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - enableWait: 'false'
          - outputTrigger_sel: 'kPWM_ValueRegister_0'
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'A'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: 'kPWM_FaultDisable_0'
              - faultState: 'kPWM_PwmFaultState0'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'B'
            - functionSel: 'notUsed'
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM2_0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - faultChannels:
      - 0:
        - commonFaultSetting:
          - clockSource: 'kPWM_BusClock'
          - faultFilterPeriod: '1'
          - faultFilterCount: '3'
          - faultGlitchStretch: 'false'
        - faults:
          - 0:
            - fault_id: 'Fault0'
            - faultClearingMode: 'kPWM_ManualNormal'
            - faultLevelR: 'high'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_RecoverFullCycle'
            - fault_int_source: 'true'
          - 1:
            - fault_id: 'Fault1'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 2:
            - fault_id: 'Fault2'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 3:
            - fault_id: 'Fault3'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'nonFiltered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
    - fault_error_interruptEn: 'true'
    - fault_error_interrupt:
      - IRQn: 'PWM4_FAULT_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'true'
      - priority: '5'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* PWM main configuration */
pwm_config_t PWM4_SM0_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_1,
  .pairOperation = kPWM_Independent,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadPwmHalfAndFullCycle,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
  .enableWait = false
};

pwm_signal_param_t PWM4_SM0_pwm_function_config[1]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .deadtimeValue = 0U
  },
};

const pwm_fault_input_filter_param_t PWM4_faultInputFilter_config = {
  .faultFilterPeriod = 1U,
  .faultFilterCount = 3U,
  .faultGlitchStretch = false
};
const pwm_fault_param_t PWM4_Fault0_fault_config = {
  .faultClearingMode = kPWM_ManualNormal,
  .faultLevel = true,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_RecoverFullCycle
};
const pwm_fault_param_t PWM4_Fault1_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM4_Fault2_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM4_Fault3_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = false,
  .recoverMode = kPWM_NoRecovery
};

static void PWM4_init(void) {
  /* Initialize PWM submodule SM0 main configuration */
  PWM_Init(PWM4_PERIPHERAL, PWM4_SM0, &PWM4_SM0_config);
  /* Initialize fault input filter configuration */
  PWM_SetupFaultInputFilter(PWM4_PERIPHERAL, &PWM4_faultInputFilter_config);
  /* Initialize fault channel 0 fault Fault0 configuration */
  PWM_SetupFaults(PWM4_PERIPHERAL, PWM4_F0_FAULT0, &PWM4_Fault0_fault_config);
  /* Initialize fault channel 0 fault Fault1 configuration */
  PWM_SetupFaults(PWM4_PERIPHERAL, PWM4_F0_FAULT1, &PWM4_Fault1_fault_config);
  /* Initialize fault channel 0 fault Fault2 configuration */
  PWM_SetupFaults(PWM4_PERIPHERAL, PWM4_F0_FAULT2, &PWM4_Fault2_fault_config);
  /* Initialize fault channel 0 fault Fault3 configuration */
  PWM_SetupFaults(PWM4_PERIPHERAL, PWM4_F0_FAULT3, &PWM4_Fault3_fault_config);
  /* Initialize submodule SM0 channel A output disable mapping to the selected faults */
  PWM_SetupFaultDisableMap(PWM4_PERIPHERAL, PWM4_SM0, PWM4_SM0_A, kPWM_faultchannel_0, (kPWM_FaultDisable_0));
  /* Enable faults interrupts */
  PWM_EnableInterrupts(PWM4_PERIPHERAL, PWM4_SM0, (kPWM_Fault0InterruptEnable));
  /* Initialize deadtime logic input for the channel A */
  PWM_SetupForceSignal(PWM4_PERIPHERAL, PWM4_SM0, PWM4_SM0_A, kPWM_UsePwm);
  /* Setup PWM output setting for submodule SM0 */
  PWM_SetupPwm(PWM4_PERIPHERAL, PWM4_SM0, PWM4_SM0_pwm_function_config, 1U, kPWM_CenterAligned, PWM4_SM0_COUNTER_FREQ_HZ, PWM4_SM0_SM_CLK_SOURCE_FREQ_HZ);
  /* Initialize output trigger for VAL0 compare of submodule SM0 */
  PWM_OutputTriggerEnable(PWM4_PERIPHERAL, PWM4_SM0, kPWM_ValueRegister_0, true);
  /* Interrupt vector PWM4_FAULT_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(PWM4_FAULT_ERROR_IRQN, PWM4_FAULT_ERROR_IRQ_PRIORITY);
  /* Interrupt PWM4_FAULT_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(PWM4_FAULT_ERROR_IRQN);  function call. */
}

/***********************************************************************************************************************
 * LPUART2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART2'
- type: 'lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART2'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '230400'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART2_config = {
  .baudRate_Bps = 230400UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART2_init(void) {
  LPUART_Init(LPUART2_PERIPHERAL, &LPUART2_config, LPUART2_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  ADC1_init();
  ADC2_init();
  ADC_ETC_init();
  CMP1_init();
  ENC1_init();
  ENC2_init();
  GPIO1_init();
  GPIO2_init();
  LPUART1_init();
  PWM1_init();
  GPIO4_init();
  ENC3_init();
  ENC4_init();
  GPIO3_init();
  LPUART3_init();
  GPIO5_init();
  LPUART4_init();
  PWM4_init();
  LPUART2_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
