/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x100030U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0xAFC00000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x0E100000U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK 0x8C000008U /*!< GPIO4 and GPIO9 share same IO MUX function, GPIO_MUX4 selects one GPIO function: affected bits mask */

/* GPIO_EMC_34 (coord D4), DO_0 */
/* Routed pin properties */
#define BOARD_INITPINS_DO_0_PERIPHERAL                                     GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DO_0_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DO_0_CHANNEL                                          20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DO_0_GPIO                                           GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DO_0_GPIO_PIN                                         20U   /*!< GPIO pin number */
#define BOARD_INITPINS_DO_0_GPIO_PIN_MASK                            (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DO_0_PORT                                           GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DO_0_PIN                                              20U   /*!< PORT pin number */
#define BOARD_INITPINS_DO_0_PIN_MASK                                 (1U << 20U)   /*!< PORT pin mask */

/* GPIO_SD_B0_00 (coord J4), PWM_UH */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_UH_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_UH_SIGNAL                                           A   /*!< Signal name */
#define BOARD_INITPINS_PWM_UH_CHANNEL                                         0U   /*!< Signal channel */

/* GPIO_SD_B0_01 (coord J3), PWM_UL */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_UL_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_UL_SIGNAL                                           B   /*!< Signal name */
#define BOARD_INITPINS_PWM_UL_CHANNEL                                         0U   /*!< Signal channel */

/* GPIO_SD_B0_02 (coord J1), PWM_VH */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_VH_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_VH_SIGNAL                                           A   /*!< Signal name */
#define BOARD_INITPINS_PWM_VH_CHANNEL                                         1U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord K1), PWM_VL */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_VL_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_VL_SIGNAL                                           B   /*!< Signal name */
#define BOARD_INITPINS_PWM_VL_CHANNEL                                         1U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord H2), PWM_WH */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_WH_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_WH_SIGNAL                                           A   /*!< Signal name */
#define BOARD_INITPINS_PWM_WH_CHANNEL                                         2U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J2), PWM_WL */
/* Routed pin properties */
#define BOARD_INITPINS_PWM_WL_PERIPHERAL                                    PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM_WL_SIGNAL                                           B   /*!< Signal name */
#define BOARD_INITPINS_PWM_WL_CHANNEL                                         2U   /*!< Signal channel */

/* GPIO_AD_B1_08 (coord H13), CUR_U */
/* Routed pin properties */
#define BOARD_INITPINS_CUR_U_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_CUR_U_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITPINS_CUR_U_CHANNEL                                         13U   /*!< Signal channel */

/* GPIO_AD_B0_14 (coord H14), CUR_V */
/* Routed pin properties */
#define BOARD_INITPINS_CUR_V_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_CUR_V_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITPINS_CUR_V_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_AD_B1_15 (coord J14), CUR_W */
/* Routed pin properties */
#define BOARD_INITPINS_CUR_W_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_CUR_W_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITPINS_CUR_W_CHANNEL                                          4U   /*!< Signal channel */

/* GPIO_AD_B1_06 (coord J12), VOLT_BUS */
/* Routed pin properties */
#define BOARD_INITPINS_VOLT_BUS_PERIPHERAL                                  ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_VOLT_BUS_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_VOLT_BUS_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_AD_B1_11 (coord J13), CUR_BUS */
/* Routed pin properties */
#define BOARD_INITPINS_CUR_BUS_OC_CMP_PERIPHERAL                            CMP1   /*!< Peripheral name */
#define BOARD_INITPINS_CUR_BUS_OC_CMP_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITPINS_CUR_BUS_OC_CMP_CHANNEL                                 6U   /*!< Signal channel */

/* GPIO_EMC_40 (coord A7), DIN_1 */
/* Routed pin properties */
#define BOARD_INITPINS_DIN_1_PERIPHERAL                                    GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DIN_1_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIN_1_CHANNEL                                         26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIN_1_GPIO                                          GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIN_1_GPIO_PIN                                        26U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIN_1_GPIO_PIN_MASK                           (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DIN_1_PORT                                          GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DIN_1_PIN                                             26U   /*!< PORT pin number */
#define BOARD_INITPINS_DIN_1_PIN_MASK                                (1U << 26U)   /*!< PORT pin mask */

/* GPIO_EMC_41 (coord C7), DIN_2 */
/* Routed pin properties */
#define BOARD_INITPINS_DIN_2_PERIPHERAL                                    GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DIN_2_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIN_2_CHANNEL                                         27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIN_2_GPIO                                          GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIN_2_GPIO_PIN                                        27U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIN_2_GPIO_PIN_MASK                           (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DIN_2_PORT                                          GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DIN_2_PIN                                             27U   /*!< PORT pin number */
#define BOARD_INITPINS_DIN_2_PIN_MASK                                (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B0_04 (coord F11), MCU_BOOT0 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_BOOT0_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_BOOT0_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_BOOT0_CHANNEL                                      4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_BOOT0_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_BOOT0_GPIO_PIN                                     4U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_BOOT0_GPIO_PIN_MASK                        (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_BOOT0_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_BOOT0_PIN                                          4U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_BOOT0_PIN_MASK                             (1U << 4U)   /*!< PORT pin mask */

/* GPIO_AD_B0_05 (coord G14), MCU_BOOT1 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_BOOT1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_BOOT1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_BOOT1_CHANNEL                                      5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_BOOT1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_BOOT1_GPIO_PIN                                     5U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_BOOT1_GPIO_PIN_MASK                        (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_BOOT1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_BOOT1_PIN                                          5U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_BOOT1_PIN_MASK                             (1U << 5U)   /*!< PORT pin mask */

/* GPIO_EMC_00 (coord E3), ENC_ANGLE_B_POS_B */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_ANGLE_B_PERIPHERAL                               ENC1   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_ANGLE_B_SIGNAL                                  PHASE   /*!< Signal name */
#define BOARD_INITPINS_ENC_ANGLE_B_CHANNEL                                     A   /*!< Signal channel */

/* GPIO_EMC_01 (coord F3), ENC_ANGLE_A_POS_A */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_ANGLE_A_PERIPHERAL                               ENC1   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_ANGLE_A_SIGNAL                                  PHASE   /*!< Signal name */
#define BOARD_INITPINS_ENC_ANGLE_A_CHANNEL                                     B   /*!< Signal channel */

/* GPIO_EMC_00 (coord E3), ENC_ANGLE_B_POS_B */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_POS_B_PERIPHERAL                                 ENC2   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_POS_B_SIGNAL                                    PHASE   /*!< Signal name */
#define BOARD_INITPINS_ENC_POS_B_CHANNEL                                       A   /*!< Signal channel */

/* GPIO_EMC_01 (coord F3), ENC_ANGLE_A_POS_A */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_POS_A_PERIPHERAL                                 ENC2   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_POS_A_SIGNAL                                    PHASE   /*!< Signal name */
#define BOARD_INITPINS_ENC_POS_A_CHANNEL                                       B   /*!< Signal channel */

/* GPIO_B1_15 (coord B14), LD_ENABLE */
/* Routed pin properties */
#define BOARD_INITPINS_LD_ENABLE_PERIPHERAL                                GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LD_ENABLE_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LD_ENABLE_CHANNEL                                     31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LD_ENABLE_GPIO                                      GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LD_ENABLE_GPIO_PIN                                    31U   /*!< GPIO pin number */
#define BOARD_INITPINS_LD_ENABLE_GPIO_PIN_MASK                       (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LD_ENABLE_PORT                                      GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LD_ENABLE_PIN                                         31U   /*!< PORT pin number */
#define BOARD_INITPINS_LD_ENABLE_PIN_MASK                            (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B0_12 (coord K14), USB_UART_TX */
/* Routed pin properties */
#define BOARD_INITPINS_USB_UART_TX_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_USB_UART_TX_SIGNAL                                     TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), USB_UART_RX */
/* Routed pin properties */
#define BOARD_INITPINS_USB_UART_RX_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_USB_UART_RX_SIGNAL                                     RX   /*!< Signal name */

/* GPIO_EMC_03 (coord G4), ENC_V */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_V_PERIPHERAL                                    GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_V_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ENC_V_CHANNEL                                          3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENC_V_GPIO                                          GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ENC_V_GPIO_PIN                                         3U   /*!< GPIO pin number */
#define BOARD_INITPINS_ENC_V_GPIO_PIN_MASK                            (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ENC_V_PORT                                          GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ENC_V_PIN                                              3U   /*!< PORT pin number */
#define BOARD_INITPINS_ENC_V_PIN_MASK                                 (1U << 3U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), SYS_TEMP */
/* Routed pin properties */
#define BOARD_INITPINS_SYS_TEMP_PERIPHERAL                                  ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_SYS_TEMP_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_SYS_TEMP_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_B1_11 (coord C13), ENC_EN */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_EN_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_EN_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ENC_EN_CHANNEL                                        27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENC_EN_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ENC_EN_GPIO_PIN                                       27U   /*!< GPIO pin number */
#define BOARD_INITPINS_ENC_EN_GPIO_PIN_MASK                          (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ENC_EN_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ENC_EN_PIN                                            27U   /*!< PORT pin number */
#define BOARD_INITPINS_ENC_EN_PIN_MASK                               (1U << 27U)   /*!< PORT pin mask */

/* GPIO_B1_13 (coord D14), LD_STB */
/* Routed pin properties */
#define BOARD_INITPINS_LD_STB_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LD_STB_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LD_STB_CHANNEL                                        29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LD_STB_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LD_STB_GPIO_PIN                                       29U   /*!< GPIO pin number */
#define BOARD_INITPINS_LD_STB_GPIO_PIN_MASK                          (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LD_STB_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LD_STB_PIN                                            29U   /*!< PORT pin number */
#define BOARD_INITPINS_LD_STB_PIN_MASK                               (1U << 29U)   /*!< PORT pin mask */

/* GPIO_EMC_27 (coord A2), LED_RED */
/* Routed pin properties */
#define BOARD_INITPINS_LED_RED_PERIPHERAL                                  GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_LED_RED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_RED_CHANNEL                                       27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO                                        GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN                                      27U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK                         (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_RED_PORT                                        GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN                                           27U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK                              (1U << 27U)   /*!< PORT pin mask */

/* GPIO_EMC_14 (coord B6), RS422_UART_RX */
/* Routed pin properties */
#define BOARD_INITPINS_RS422_UART_RX_PERIPHERAL                          LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_RS422_UART_RX_SIGNAL                                   RX   /*!< Signal name */

/* GPIO_EMC_13 (coord A6), RS422_UART_TX */
/* Routed pin properties */
#define BOARD_INITPINS_RS422_UART_TX_PERIPHERAL                          LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_RS422_UART_TX_SIGNAL                                   TX   /*!< Signal name */

/* GPIO_EMC_04 (coord F2), ENC_ANGLE_Z */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_ANGLE_Z_PERIPHERAL                               ENC1   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_ANGLE_Z_SIGNAL                                  INDEX   /*!< Signal name */

/* GPIO_EMC_19 (coord B4), UART4_TX */
/* Routed pin properties */
#define BOARD_INITPINS_UART4_TX_PERIPHERAL                               LPUART4   /*!< Peripheral name */
#define BOARD_INITPINS_UART4_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_EMC_20 (coord A3), UART4_RX */
/* Routed pin properties */
#define BOARD_INITPINS_UART4_RX_PERIPHERAL                               LPUART4   /*!< Peripheral name */
#define BOARD_INITPINS_UART4_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_EMC_39 (coord B7), DIN_0 */
/* Routed pin properties */
#define BOARD_INITPINS_DIN_0_PERIPHERAL                                    GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DIN_0_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIN_0_CHANNEL                                         25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIN_0_GPIO                                          GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIN_0_GPIO_PIN                                        25U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIN_0_GPIO_PIN_MASK                           (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DIN_0_PORT                                          GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DIN_0_PIN                                             25U   /*!< PORT pin number */
#define BOARD_INITPINS_DIN_0_PIN_MASK                                (1U << 25U)   /*!< PORT pin mask */

/* GPIO_EMC_26 (coord B3), LED_G */
/* Routed pin properties */
#define BOARD_INITPINS_LED_G_PERIPHERAL                                    GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_LED_G_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_G_CHANNEL                                         26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_G_GPIO                                          GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_G_GPIO_PIN                                        26U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_G_GPIO_PIN_MASK                           (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_G_PORT                                          GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_G_PIN                                             26U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_G_PIN_MASK                                (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), Light_PWM */
/* Routed pin properties */
#define BOARD_INITPINS_Light_PWM_PERIPHERAL                                 PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_Light_PWM_SIGNAL                                        A   /*!< Signal name */
#define BOARD_INITPINS_Light_PWM_CHANNEL                                      2U   /*!< Signal channel */

/* GPIO_AD_B1_13 (coord H11), Light_V_Out */
/* Routed pin properties */
#define BOARD_INITPINS_Light_V_Out_PERIPHERAL                               ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_Light_V_Out_SIGNAL                                     IN   /*!< Signal name */
#define BOARD_INITPINS_Light_V_Out_CHANNEL                                    2U   /*!< Signal channel */

/* GPIO_EMC_31 (coord C5), DI_A */
/* Routed pin properties */
#define BOARD_INITPINS_DI_A_PERIPHERAL                                     GPIO4   /*!< Peripheral name */
#define BOARD_INITPINS_DI_A_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_A_CHANNEL                                          31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_A_GPIO                                           GPIO4   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_A_GPIO_PIN                                         31U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_A_GPIO_PIN_MASK                            (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_A_PORT                                           GPIO4   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_A_PIN                                              31U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_A_PIN_MASK                                 (1U << 31U)   /*!< PORT pin mask */

/* GPIO_B1_06 (coord C12), HSIO3 */
/* Routed pin properties */
#define BOARD_INITPINS_HSIO3_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_HSIO3_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_HSIO3_CHANNEL                                         22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HSIO3_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HSIO3_GPIO_PIN                                        22U   /*!< GPIO pin number */
#define BOARD_INITPINS_HSIO3_GPIO_PIN_MASK                           (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_HSIO3_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_HSIO3_PIN                                             22U   /*!< PORT pin number */
#define BOARD_INITPINS_HSIO3_PIN_MASK                                (1U << 22U)   /*!< PORT pin mask */

/* GPIO_B1_07 (coord B12), HSIO1 */
/* Routed pin properties */
#define BOARD_INITPINS_HSIO1_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_HSIO1_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_HSIO1_CHANNEL                                         23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HSIO1_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HSIO1_GPIO_PIN                                        23U   /*!< GPIO pin number */
#define BOARD_INITPINS_HSIO1_GPIO_PIN_MASK                           (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_HSIO1_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_HSIO1_PIN                                             23U   /*!< PORT pin number */
#define BOARD_INITPINS_HSIO1_PIN_MASK                                (1U << 23U)   /*!< PORT pin mask */

/* GPIO_B1_08 (coord A12), HSIO2 */
/* Routed pin properties */
#define BOARD_INITPINS_HSIO2_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_HSIO2_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_HSIO2_CHANNEL                                         24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HSIO2_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HSIO2_GPIO_PIN                                        24U   /*!< GPIO pin number */
#define BOARD_INITPINS_HSIO2_GPIO_PIN_MASK                           (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_HSIO2_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_HSIO2_PIN                                             24U   /*!< PORT pin number */
#define BOARD_INITPINS_HSIO2_PIN_MASK                                (1U << 24U)   /*!< PORT pin mask */

/* GPIO_B1_09 (coord A13), HSIO4 */
/* Routed pin properties */
#define BOARD_INITPINS_HSIO4_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_HSIO4_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_HSIO4_CHANNEL                                         25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HSIO4_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HSIO4_GPIO_PIN                                        25U   /*!< GPIO pin number */
#define BOARD_INITPINS_HSIO4_GPIO_PIN_MASK                           (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_HSIO4_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_HSIO4_PIN                                             25U   /*!< PORT pin number */
#define BOARD_INITPINS_HSIO4_PIN_MASK                                (1U << 25U)   /*!< PORT pin mask */

/* GPIO_B1_10 (coord B13), HSIO5 */
/* Routed pin properties */
#define BOARD_INITPINS_HSIO5_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_HSIO5_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_HSIO5_CHANNEL                                         26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HSIO5_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HSIO5_GPIO_PIN                                        26U   /*!< GPIO pin number */
#define BOARD_INITPINS_HSIO5_GPIO_PIN_MASK                           (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_HSIO5_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_HSIO5_PIN                                             26U   /*!< PORT pin number */
#define BOARD_INITPINS_HSIO5_PIN_MASK                                (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (coord L12), UART2_SEL */
/* Routed pin properties */
#define BOARD_INITPINS_UART2_SEL_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_UART2_SEL_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_UART2_SEL_CHANNEL                                     20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_UART2_SEL_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_UART2_SEL_GPIO_PIN                                    20U   /*!< GPIO pin number */
#define BOARD_INITPINS_UART2_SEL_GPIO_PIN_MASK                       (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_UART2_SEL_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_UART2_SEL_PIN                                         20U   /*!< PORT pin number */
#define BOARD_INITPINS_UART2_SEL_PIN_MASK                            (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_02 (coord L11), UART2_TX */
/* Routed pin properties */
#define BOARD_INITPINS_UART2_TX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_UART2_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_AD_B1_03 (coord M12), UART2_RX */
/* Routed pin properties */
#define BOARD_INITPINS_UART2_RX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_UART2_RX_SIGNAL                                        RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
