/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 9.0.1
pin_labels:
- {pin_num: L11, pin_signal: GPIO_AD_B1_02, label: UART2_TX, identifier: DI_10;UART2_TX}
- {pin_num: L12, pin_signal: GPIO_AD_B1_04, label: UART2_SEL, identifier: MCU_TP4;UART2_SEL}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: MCU_TP6, identifier: MCU_TP6}
- {pin_num: M11, pin_signal: GPIO_AD_B0_02, label: DI_6, identifier: DI_6}
- {pin_num: M12, pin_signal: GPIO_AD_B1_03, label: UART2_RX, identifier: MCU_TP3;UART2_RX}
- {pin_num: M13, pin_signal: GPIO_AD_B1_09, label: MCU_TP5, identifier: MCU_TP5}
- {pin_num: C1, pin_signal: GPIO_EMC_21, label: LED_G5, identifier: LED_G5}
- {pin_num: C2, pin_signal: GPIO_EMC_09, label: LED_G1, identifier: LED_G1}
- {pin_num: C3, pin_signal: GPIO_EMC_36, label: MCU_SW7, identifier: MCU_SW7}
- {pin_num: C4, pin_signal: GPIO_EMC_33, label: MCU_SW4, identifier: MCU_SW4}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: MCU_SW5, identifier: MCU_SW5}
- {pin_num: B2, pin_signal: GPIO_EMC_18, label: MCU_SW1, identifier: MCU_SW1}
- {pin_num: D2, pin_signal: GPIO_EMC_25, label: LED_G4, identifier: LED_G4}
- {pin_num: D3, pin_signal: GPIO_EMC_24, label: MCU_SW6, identifier: MCU_SW6}
- {pin_num: D4, pin_signal: GPIO_EMC_34, label: DO_0, identifier: LED_G3;DO_0}
- {pin_num: D5, pin_signal: GPIO_EMC_32, label: MCU_SW3, identifier: MCU_SW3}
- {pin_num: J4, pin_signal: GPIO_SD_B0_00, label: PWM_UH, identifier: PWM_UH}
- {pin_num: J3, pin_signal: GPIO_SD_B0_01, label: PWM_UL, identifier: PWM_UL}
- {pin_num: J1, pin_signal: GPIO_SD_B0_02, label: PWM_VH, identifier: PWM_VH}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: PWM_VL, identifier: PWM_VL}
- {pin_num: H2, pin_signal: GPIO_SD_B0_04, label: PWM_WH, identifier: PWM_WH}
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: PWM_WL, identifier: PWM_WL}
- {pin_num: H13, pin_signal: GPIO_AD_B1_08, label: CUR_U, identifier: CUR_U}
- {pin_num: H14, pin_signal: GPIO_AD_B0_14, label: CUR_V, identifier: CUR_V}
- {pin_num: J14, pin_signal: GPIO_AD_B1_15, label: CUR_W, identifier: CUR_W}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: CUR_BUS, identifier: CUR_BUS;CUR_BUS_OC_CMP}
- {pin_num: J11, pin_signal: GPIO_AD_B1_00, label: DI_9, identifier: DI_9}
- {pin_num: H11, pin_signal: GPIO_AD_B1_13, label: Light_V_Out, identifier: DOUT9;Light_V_Out}
- {pin_num: J12, pin_signal: GPIO_AD_B1_06, label: VOLT_BUS, identifier: VOLT_BUS;VOLT_BUS_OV_CMP;}
- {pin_num: L3, pin_signal: GPIO_SD_B1_06, label: MCU_TP13, identifier: MCU_TP13}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: SPI_HMI_SCS, identifier: SPI_HMI_SCS}
- {pin_num: D8, pin_signal: GPIO_B0_03, label: SPI_HMI_SCK, identifier: SPI_HMI_SCK}
- {pin_num: E7, pin_signal: GPIO_B0_01, label: SPI_HMI_SDI, identifier: SPI_HMI_SDI}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: SPI_HMI_SDO, identifier: SPI_HMI_SDO}
- {pin_num: C6, pin_signal: GPIO_EMC_30, label: MCU_SW2, identifier: MCU_SW2}
- {pin_num: A7, pin_signal: GPIO_EMC_40, label: DIN_1, identifier: MCU_SW8;DIN_1}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: DIN_2, identifier: MCU_TP1;DIN_2}
- {pin_num: G1, pin_signal: GPIO_EMC_10, label: LED_G2, identifier: LED_G2}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: MCU_BOOT0, identifier: MCU_BOOT0}
- {pin_num: G14, pin_signal: GPIO_AD_B0_05, label: MCU_BOOT1, identifier: MCU_BOOT1}
- {pin_num: F1, pin_signal: GPIO_EMC_22, label: ENC_EN, identifier: ENC_EN}
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: ENC_ANGLE_A_POS_A, identifier: ENC_ANGLE_A;ENC_POS_A}
- {pin_num: E3, pin_signal: GPIO_EMC_00, label: ENC_ANGLE_B_POS_B, identifier: ENC_ANGLE_B;ENC_POS_B}
- {pin_num: F2, pin_signal: GPIO_EMC_04, label: ENC_ANGLE_Z, identifier: ENC_ANGLE_Z}
- {pin_num: K14, pin_signal: GPIO_AD_B0_12, label: USB_UART_TX, identifier: USB_UART_TX}
- {pin_num: L14, pin_signal: GPIO_AD_B0_13, label: USB_UART_RX, identifier: USB_UART_RX}
- {pin_num: K12, pin_signal: GPIO_AD_B1_05, label: USB_UART_DET, identifier: USB_UART_DET}
- {pin_num: K11, pin_signal: GPIO_AD_B1_01, label: USB_UART_RST, identifier: USB_UART_RST}
- {pin_num: G2, pin_signal: GPIO_EMC_23, label: LED_G6, identifier: LED_G6}
- {pin_num: G3, pin_signal: GPIO_EMC_11, label: ENC_U, identifier: ENC_U}
- {pin_num: G4, pin_signal: GPIO_EMC_03, label: ENC_V, identifier: ENC_V}
- {pin_num: G5, pin_signal: GPIO_EMC_05, label: ENC_W, identifier: ENC_W}
- {pin_num: H5, pin_signal: GPIO_EMC_06, label: LED_B1, identifier: LED_B1}
- {pin_num: H4, pin_signal: GPIO_EMC_07, label: LED_B2, identifier: LED_B2}
- {pin_num: H3, pin_signal: GPIO_EMC_08, label: LED_B3, identifier: LED_B3}
- {pin_num: E5, pin_signal: GPIO_EMC_35, label: LED_G7, identifier: LED_G7}
- {pin_num: K10, pin_signal: GPIO_AD_B1_07, label: SYS_TEMP, identifier: MCU_TP2;TEMP;SYS_TEMP}
- {pin_num: M5, pin_signal: GPIO_SD_B1_01, label: MCU_TP7, identifier: MCU_TP7}
- {pin_num: M4, pin_signal: GPIO_SD_B1_03, label: MCU_TP8, identifier: MCU_TP8}
- {pin_num: L5, pin_signal: GPIO_SD_B1_00, label: MCU_TP9, identifier: MCU_TP9}
- {pin_num: M3, pin_signal: GPIO_SD_B1_02, label: MCU_TP10, identifier: MCU_TP10}
- {pin_num: P2, pin_signal: GPIO_SD_B1_04, label: MCU_TP11, identifier: MCU_TP11}
- {pin_num: N3, pin_signal: GPIO_SD_B1_05, label: MCU_TP12, identifier: MCU_TP12}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: HSIO1, identifier: DI_0;HSIO1}
- {pin_num: A12, pin_signal: GPIO_B1_08, label: HSIO2, identifier: DI_1;HSIO2}
- {pin_num: A13, pin_signal: GPIO_B1_09, label: HSIO4, identifier: DI_2;HSIO4}
- {pin_num: B13, pin_signal: GPIO_B1_10, label: HSIO5, identifier: DI_3;HSIO5}
- {pin_num: B14, pin_signal: GPIO_B1_15, label: LD_ENABLE, identifier: DI_4;LD_ENABLE}
- {pin_num: H10, pin_signal: GPIO_AD_B0_01, label: DI_5, identifier: DI_5}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: DI_7, identifier: DI_7}
- {pin_num: C12, pin_signal: GPIO_B1_06, label: HSIO3, identifier: DOUT0;HSIO3}
- {pin_num: C13, pin_signal: GPIO_B1_11, label: ENC_EN, identifier: DOUT1;ENC_EN}
- {pin_num: C14, pin_signal: GPIO_B1_14, label: Light_PWM, identifier: DOUT2;Light_PWM}
- {pin_num: D11, pin_signal: GPIO_B1_03, label: DOUT3, identifier: DOUT3}
- {pin_num: D12, pin_signal: GPIO_B1_05, label: DOUT4, identifier: DOUT4}
- {pin_num: D13, pin_signal: GPIO_B1_12, label: DOUT5, identifier: DOUT5}
- {pin_num: D14, pin_signal: GPIO_B1_13, label: LD_STB, identifier: DOUT6;LD_STB}
- {pin_num: E12, pin_signal: GPIO_B1_04, label: DOUT7, identifier: DOUT7}
- {pin_num: M14, pin_signal: GPIO_AD_B0_00, label: DOUT8, identifier: DOUT8}
- {pin_num: G12, pin_signal: GPIO_AD_B1_14, label: DOUT10, identifier: DOUT10}
- {pin_num: H12, pin_signal: GPIO_AD_B1_12, label: TEMP, identifier: TEMP}
- {pin_num: A2, pin_signal: GPIO_EMC_27, label: LED_RED, identifier: SPI_COMM_SCK;LED_RED}
- {pin_num: D1, pin_signal: GPIO_EMC_28, label: SPI_COMM_SDO, identifier: SPI_COMM_SDO}
- {pin_num: E1, pin_signal: GPIO_EMC_29, label: SPI_COMM_SDI, identifier: SPI_COMM_SDI}
- {pin_num: C5, pin_signal: GPIO_EMC_31, label: DI_A, identifier: SPI_COMM_SCS;DI_A}
- {pin_num: F4, pin_signal: GPIO_EMC_02, label: PULSE, identifier: PULSE_PLS_CW;PULSE_CCW}
- {pin_num: E4, pin_signal: GPIO_EMC_37, label: PULSE, identifier: PULSE_DIR}
- {pin_num: A6, pin_signal: GPIO_EMC_13, label: RS422_UART_TX, identifier: RS422_UART_TX}
- {pin_num: B6, pin_signal: GPIO_EMC_14, label: RS422_UART_RX, identifier: RS422_UART_RX}
- {pin_num: L10, pin_signal: GPIO_AD_B0_15, label: DI_8, identifier: DI_8}
- {pin_num: B4, pin_signal: GPIO_EMC_19, label: UART4_TX, identifier: UART4_TX}
- {pin_num: A3, pin_signal: GPIO_EMC_20, label: UART4_RX, identifier: UART4_RX}
- {pin_num: B7, pin_signal: GPIO_EMC_39, label: DIN_0, identifier: DIN_0}
- {pin_num: B3, pin_signal: GPIO_EMC_26, label: LED_G, identifier: LED_G}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D4, peripheral: GPIO3, signal: 'gpio_io, 20', pin_signal: GPIO_EMC_34, identifier: DO_0, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: J4, peripheral: PWM1, signal: 'A, 0', pin_signal: GPIO_SD_B0_00, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: J3, peripheral: PWM1, signal: 'B, 0', pin_signal: GPIO_SD_B0_01, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: J1, peripheral: PWM1, signal: 'A, 1', pin_signal: GPIO_SD_B0_02, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: K1, peripheral: PWM1, signal: 'B, 1', pin_signal: GPIO_SD_B0_03, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: H2, peripheral: PWM1, signal: 'A, 2', pin_signal: GPIO_SD_B0_04, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: J2, peripheral: PWM1, signal: 'B, 2', pin_signal: GPIO_SD_B0_05, direction: OUTPUT, pull_up_down_config: Pull_Down_100K_Ohm}
  - {peripheral: PWM1, signal: 'FAULT, 1', pin_signal: LOGIC_LOW}
  - {peripheral: PWM1, signal: 'FAULT, 2', pin_signal: LOGIC_LOW}
  - {peripheral: PWM1, signal: 'FAULT, 3', pin_signal: LOGIC_LOW}
  - {pin_num: H13, peripheral: ADC1, signal: 'IN, 13', pin_signal: GPIO_AD_B1_08}
  - {pin_num: H14, peripheral: ADC1, signal: 'IN, 3', pin_signal: GPIO_AD_B0_14}
  - {pin_num: J14, peripheral: ADC2, signal: 'IN, 4', pin_signal: GPIO_AD_B1_15}
  - {pin_num: J12, peripheral: ADC1, signal: 'IN, 11', pin_signal: GPIO_AD_B1_06, identifier: VOLT_BUS}
  - {pin_num: J13, peripheral: CMP1, signal: 'IN, 6', pin_signal: GPIO_AD_B1_11, identifier: CUR_BUS_OC_CMP}
  - {peripheral: ADC_ETC, signal: 'XBAR0_TRIG, 0', pin_signal: FLEXPWM1_PWM1_OUT_TRIG0_1}
  - {peripheral: ADC_ETC, signal: 'XBAR1_TRIG, 0', pin_signal: FLEXPWM1_PWM1_OUT_TRIG0_1}
  - {pin_num: A7, peripheral: GPIO3, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_40, identifier: DIN_1, direction: INPUT}
  - {pin_num: C7, peripheral: GPIO3, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_41, identifier: DIN_2, direction: INPUT}
  - {pin_num: F11, peripheral: GPIO1, signal: 'gpio_io, 04', pin_signal: GPIO_AD_B0_04, direction: INPUT}
  - {pin_num: G14, peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO_AD_B0_05, direction: INPUT}
  - {pin_num: E3, peripheral: ENC1, signal: 'PHASE, A', pin_signal: GPIO_EMC_00, identifier: ENC_ANGLE_B}
  - {pin_num: F3, peripheral: ENC1, signal: 'PHASE, B', pin_signal: GPIO_EMC_01, identifier: ENC_ANGLE_A}
  - {peripheral: ENC1, signal: TRG, pin_signal: FLEXPWM1_PWM1_OUT_TRIG0_1}
  - {pin_num: E3, peripheral: ENC2, signal: 'PHASE, A', pin_signal: GPIO_EMC_00, identifier: ENC_POS_B}
  - {pin_num: F3, peripheral: ENC2, signal: 'PHASE, B', pin_signal: GPIO_EMC_01, identifier: ENC_POS_A}
  - {peripheral: ENC2, signal: TRG, pin_signal: FLEXPWM1_PWM1_OUT_TRIG0_1}
  - {pin_num: B14, peripheral: GPIO2, signal: 'gpio_io, 31', pin_signal: GPIO_B1_15, identifier: LD_ENABLE, direction: OUTPUT, pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12}
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13}
  - {peripheral: PWM1, signal: 'FAULT, 0', pin_signal: ACMP1_OUT}
  - {pin_num: G4, peripheral: GPIO4, signal: 'gpio_io, 03', pin_signal: GPIO_EMC_03, direction: INPUT}
  - {pin_num: K10, peripheral: ADC1, signal: 'IN, 12', pin_signal: GPIO_AD_B1_07, identifier: SYS_TEMP, direction: INPUT}
  - {pin_num: C13, peripheral: GPIO2, signal: 'gpio_io, 27', pin_signal: GPIO_B1_11, identifier: ENC_EN, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: D14, peripheral: GPIO2, signal: 'gpio_io, 29', pin_signal: GPIO_B1_13, identifier: LD_STB, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: A2, peripheral: GPIO4, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_27, identifier: LED_RED, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: B6, peripheral: LPUART3, signal: RX, pin_signal: GPIO_EMC_14}
  - {pin_num: A6, peripheral: LPUART3, signal: TX, pin_signal: GPIO_EMC_13}
  - {pin_num: F2, peripheral: ENC1, signal: INDEX, pin_signal: GPIO_EMC_04}
  - {pin_num: B4, peripheral: LPUART4, signal: TX, pin_signal: GPIO_EMC_19}
  - {pin_num: A3, peripheral: LPUART4, signal: RX, pin_signal: GPIO_EMC_20}
  - {pin_num: B7, peripheral: GPIO3, signal: 'gpio_io, 25', pin_signal: GPIO_EMC_39, direction: INPUT}
  - {pin_num: B3, peripheral: GPIO4, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_26, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: C14, peripheral: PWM4, signal: 'A, 2', pin_signal: GPIO_B1_14, identifier: Light_PWM, direction: OUTPUT}
  - {pin_num: H11, peripheral: ADC2, signal: 'IN, 2', pin_signal: GPIO_AD_B1_13, identifier: Light_V_Out}
  - {pin_num: C5, peripheral: GPIO4, signal: 'gpio_io, 31', pin_signal: GPIO_EMC_31, identifier: DI_A, direction: INPUT}
  - {pin_num: C12, peripheral: GPIO2, signal: 'gpio_io, 22', pin_signal: GPIO_B1_06, identifier: HSIO3, direction: OUTPUT}
  - {pin_num: B12, peripheral: GPIO2, signal: 'gpio_io, 23', pin_signal: GPIO_B1_07, identifier: HSIO1, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: A12, peripheral: GPIO2, signal: 'gpio_io, 24', pin_signal: GPIO_B1_08, identifier: HSIO2, direction: OUTPUT}
  - {pin_num: A13, peripheral: GPIO2, signal: 'gpio_io, 25', pin_signal: GPIO_B1_09, identifier: HSIO4, direction: INPUT}
  - {pin_num: B13, peripheral: GPIO2, signal: 'gpio_io, 26', pin_signal: GPIO_B1_10, identifier: HSIO5, direction: OUTPUT, gpio_init_state: 'true', software_input_on: Disable,
    hysteresis_enable: Disable, pull_up_down_config: Pull_Up_47K_Ohm, pull_keeper_select: Keeper}
  - {pin_num: E14, peripheral: JTAG, signal: TMS, pin_signal: GPIO_AD_B0_06}
  - {pin_num: F12, peripheral: JTAG, signal: TCK, pin_signal: GPIO_AD_B0_07}
  - {pin_num: F13, peripheral: JTAG, signal: MOD, pin_signal: GPIO_AD_B0_08}
  - {pin_num: F14, peripheral: JTAG, signal: TDI, pin_signal: GPIO_AD_B0_09}
  - {pin_num: G13, peripheral: JTAG, signal: TDO, pin_signal: GPIO_AD_B0_10}
  - {pin_num: G10, peripheral: JTAG, signal: TRSTB, pin_signal: GPIO_AD_B0_11}
  - {pin_num: L12, peripheral: GPIO1, signal: 'gpio_io, 20', pin_signal: GPIO_AD_B1_04, identifier: UART2_SEL, direction: OUTPUT}
  - {pin_num: L11, peripheral: LPUART2, signal: TX, pin_signal: GPIO_AD_B1_02, identifier: UART2_TX}
  - {pin_num: M12, peripheral: LPUART2, signal: RX, pin_signal: GPIO_AD_B1_03, identifier: UART2_RX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           
  CLOCK_EnableClock(kCLOCK_Xbar1);            

  /* GPIO configuration of MCU_BOOT0 on GPIO_AD_B0_04 (pin F11) */
  gpio_pin_config_t MCU_BOOT0_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_04 (pin F11) */
  GPIO_PinInit(GPIO1, 4U, &MCU_BOOT0_config);

  /* GPIO configuration of MCU_BOOT1 on GPIO_AD_B0_05 (pin G14) */
  gpio_pin_config_t MCU_BOOT1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_05 (pin G14) */
  GPIO_PinInit(GPIO1, 5U, &MCU_BOOT1_config);

  /* GPIO configuration of UART2_SEL on GPIO_AD_B1_04 (pin L12) */
  gpio_pin_config_t UART2_SEL_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_04 (pin L12) */
  GPIO_PinInit(GPIO1, 20U, &UART2_SEL_config);

  /* GPIO configuration of HSIO3 on GPIO_B1_06 (pin C12) */
  gpio_pin_config_t HSIO3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_06 (pin C12) */
  GPIO_PinInit(GPIO2, 22U, &HSIO3_config);

  /* GPIO configuration of HSIO1 on GPIO_B1_07 (pin B12) */
  gpio_pin_config_t HSIO1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_07 (pin B12) */
  GPIO_PinInit(GPIO2, 23U, &HSIO1_config);

  /* GPIO configuration of HSIO2 on GPIO_B1_08 (pin A12) */
  gpio_pin_config_t HSIO2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_08 (pin A12) */
  GPIO_PinInit(GPIO2, 24U, &HSIO2_config);

  /* GPIO configuration of HSIO4 on GPIO_B1_09 (pin A13) */
  gpio_pin_config_t HSIO4_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_09 (pin A13) */
  GPIO_PinInit(GPIO2, 25U, &HSIO4_config);

  /* GPIO configuration of HSIO5 on GPIO_B1_10 (pin B13) */
  gpio_pin_config_t HSIO5_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_10 (pin B13) */
  GPIO_PinInit(GPIO2, 26U, &HSIO5_config);

  /* GPIO configuration of ENC_EN on GPIO_B1_11 (pin C13) */
  gpio_pin_config_t ENC_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_11 (pin C13) */
  GPIO_PinInit(GPIO2, 27U, &ENC_EN_config);

  /* GPIO configuration of LD_STB on GPIO_B1_13 (pin D14) */
  gpio_pin_config_t LD_STB_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_13 (pin D14) */
  GPIO_PinInit(GPIO2, 29U, &LD_STB_config);

  /* GPIO configuration of LD_ENABLE on GPIO_B1_15 (pin B14) */
  gpio_pin_config_t LD_ENABLE_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_15 (pin B14) */
  GPIO_PinInit(GPIO2, 31U, &LD_ENABLE_config);

  /* GPIO configuration of DO_0 on GPIO_EMC_34 (pin D4) */
  gpio_pin_config_t DO_0_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_34 (pin D4) */
  GPIO_PinInit(GPIO3, 20U, &DO_0_config);

  /* GPIO configuration of DIN_0 on GPIO_EMC_39 (pin B7) */
  gpio_pin_config_t DIN_0_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_39 (pin B7) */
  GPIO_PinInit(GPIO3, 25U, &DIN_0_config);

  /* GPIO configuration of DIN_1 on GPIO_EMC_40 (pin A7) */
  gpio_pin_config_t DIN_1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_40 (pin A7) */
  GPIO_PinInit(GPIO3, 26U, &DIN_1_config);

  /* GPIO configuration of DIN_2 on GPIO_EMC_41 (pin C7) */
  gpio_pin_config_t DIN_2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_41 (pin C7) */
  GPIO_PinInit(GPIO3, 27U, &DIN_2_config);

  /* GPIO configuration of ENC_V on GPIO_EMC_03 (pin G4) */
  gpio_pin_config_t ENC_V_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_03 (pin G4) */
  GPIO_PinInit(GPIO4, 3U, &ENC_V_config);

  /* GPIO configuration of LED_G on GPIO_EMC_26 (pin B3) */
  gpio_pin_config_t LED_G_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_26 (pin B3) */
  GPIO_PinInit(GPIO4, 26U, &LED_G_config);

  /* GPIO configuration of LED_RED on GPIO_EMC_27 (pin A2) */
  gpio_pin_config_t LED_RED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_27 (pin A2) */
  GPIO_PinInit(GPIO4, 27U, &LED_RED_config);

  /* GPIO configuration of DI_A on GPIO_EMC_31 (pin C5) */
  gpio_pin_config_t DI_A_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_31 (pin C5) */
  GPIO_PinInit(GPIO4, 31U, &DI_A_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_04_GPIO1_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_JTAG_TMS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_JTAG_TCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_08_JTAG_MOD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_JTAG_TDI, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_JTAG_TDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_JTAG_TRSTB, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_GPIO1_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_LPUART2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_LPUART2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_GPIO1_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_GPIO1_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_06_GPIO2_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_07_GPIO2_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_08_GPIO2_IO24, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_09_GPIO2_IO25, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_10_GPIO2_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_11_GPIO2_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_13_GPIO2_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_FLEXPWM4_PWMA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_XBAR1_XBAR_IN02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_XBAR1_IN03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_GPIO4_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_XBAR1_INOUT06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_LPUART3_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_14_LPUART3_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_LPUART4_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_20_LPUART4_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_26_GPIO4_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_27_GPIO4_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_GPIO4_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_GPIO3_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_39_GPIO3_IO25, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_40_GPIO3_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_41_GPIO3_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_FLEXPWM1_PWMA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_FLEXPWM1_PWMB00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_FLEXPWM1_PWMA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_FLEXPWM1_PWMB01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_FLEXPWM1_PWMA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_FLEXPWM1_PWMB02, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR28 = ((IOMUXC_GPR->GPR28 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR29 = ((IOMUXC_GPR->GPR29 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_6_MASK))) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_6(0x00U) 
    );
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAcmp1Out, kXBARA1_OutputFlexpwm1Fault0); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputLogicLow, kXBARA1_OutputFlexpwm1Fault1); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputLogicLow, kXBARA1_OutputFlexpwm1234Fault2); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputLogicLow, kXBARA1_OutputFlexpwm1234Fault3); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn02, kXBARA1_OutputEnc1PhaseAInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn03, kXBARA1_OutputEnc1PhaseBInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout06, kXBARA1_OutputEnc1Index); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputFlexpwm1Pwm1OutTrig01, kXBARA1_OutputEnc1Trigger); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn02, kXBARA1_OutputEnc2PhaseAInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn03, kXBARA1_OutputEnc2PhaseBInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputFlexpwm1Pwm1OutTrig01, kXBARA1_OutputEnc2Trigger); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputFlexpwm1Pwm1OutTrig01, kXBARA1_OutputAdcEtcXbar0Trig0); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputFlexpwm1Pwm1OutTrig01, kXBARA1_OutputAdcEtcXbar1Trig0); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_10_GPIO2_IO26, 0x50B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0xD0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_FLEXPWM1_PWMA00, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_FLEXPWM1_PWMB00, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_02_FLEXPWM1_PWMA01, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_03_FLEXPWM1_PWMB01, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_04_FLEXPWM1_PWMA02, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_05_FLEXPWM1_PWMB02, 0x10B0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
